### PR TITLE
Make code compatible with Python3 (+ small bugfix)

### PR DESCRIPTION
**Pull request by zbeloki**
File setup.py declares this module supports Python3: "Programming Language :: Python :: 3.6". But the code is only compatible with Python2. This pull request contains a couple of small fixes to make it compatible with Python3.

I'm not sure it should also be compatible with Python2 or not.

In addition, it contains a small bugfix.

### CODE REVIEW

**Comment by zbeloki** [comment]
More fixes are needed to make it fully compatible with Python3.

**Comment by josubg** [comment]
Hi ¿how the changes affects to python 2 compatibility?

**Comment by ragerri** [comment]
In any way. I started doing the migration because I wanted to add the
opinions layer but I will backtrack to being compatible with python 2 only.
I will open a python3 branch just in case anyone wants to make it python3
compatible.

R

**Comment by zbeloki** [comment]
> Hi ¿how the changes affects to python 2 compatibility?

It wouldn't be python2 compatible after the changes.

> In any way. I started doing the migration because I wanted to add the opinions layer but I will backtrack to being compatible with python 2 only. I will open a python3 branch just in case anyone wants to make it python3 compatible. R

OK. Eskerrik asko!

**Comment by ragerri** [comment]
Hello, 

I have created a python3 branch, can you please move your pull request (all 6 commits) to that branch so we can merge your code there?

Mila esker,

R

**Comment by zbeloki** [comment]
Hi Rodri,

Could you please merge this PR to the python3 branch? Or is there any problem with it?

Thanks!

**Pull request merged**
